<?php
$header = $this->themeSettingAssetUrl('header') ? $this->themeSettingAssetUrl('header') : 'https://placeimg.com/783/834/any';
?>
<section id="imgBanner" style="background-image: url('<?php echo $header ?>')">
  <div class="container">
    <div class="searchbox px-4 py-5 my-5 text-center">
      <h1 class="display-5">Hidden Collections Registry</h1>
      <div class="col-lg-5 mx-auto">
          <?php echo $this->partial('common/search-form'); ?>
          <div class="sample-searches">
            <p>
              <strong>Sample Searches:</strong>
              <span id="samples">
                <a class="btn btn-sm btn-inverse-ghost" aria-label="Sample Search: &quot;Natural History&quot;" href="search?q=natural+history">Natural History</a>
                <a class="btn btn-sm btn-inverse-ghost" aria-label="Sample Search: Ethnomusicology" href="search?q=natural+historyEthnomusicology">Ethnomusicology</a>
                <a class="btn btn-sm btn-inverse-ghost" aria-label="Sample Search: Mapas históricos" href="search?q=natural+historyMapas%20históricos">Mapas históricos</a>
              </span>
            </p>
          </div>
      </div>
    </div>
  </div>
</section>
